version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: stock-db
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init-scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "--user=root", "--password=${MYSQL_ROOT_PASSWORD}" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s
    restart: unless-stopped
    networks:
      - app-network
    deploy:
      resources:
        limits:
          memory: 512M
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  stock-price-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: stock-price-app
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      # API Configuration
      POLYGON_API_KEY: ${POLYGON_API_KEY}

      # Database Configuration
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/${MYSQL_DATABASE}?createDatabaseIfNotExist=true&serverTimezone=UTC&useSSL=false
      SPRING_DATASOURCE_USERNAME: ${MYSQL_USER}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD}

      # JPA Configuration
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: false

      # JVM Options
      JAVA_OPTS: "-Xms256m -Xmx512m -XX:+UseContainerSupport"

      # Spring Profile
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE:-dev}

      # Log Configuration
      ROOT_LOG_LEVEL: ${ROOT_LOG_LEVEL}
      POLYGON_API_LOG_LEVEL: ${POLYGON_API_LOG_LEVEL}
      POLYGON_API_CONFIG_LOG_LEVEL: ${POLYGON_API_CONFIG_LOG_LEVEL}
      LOG_FILE_PATH: ${LOG_FILE_PATH:-/app/logs/polygon-api.log}
    ports:
      - "127.0.0.1:8080:8080"
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 60s
    restart: unless-stopped
    networks:
      - app-network
    deploy:
      resources:
        limits:
          memory: 768M
    volumes:
      - ./logs:/app/logs

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:
    driver: local